### ISSUE TITLE
simulation environment

### ISSUE THREAD

**Issue by ning-zelin** [robotic-esp/see-public#2]
Hello, I am interested in your work and would like to get the code running and view the results in rviz. Can you please tell me if there is an open source configuration for simulation and visualization, thank you.

**Comment by rowanborder** [comment]
Hi @ning-zelin, thanks for your interest in SEE. Unfortunately we don't plan to make the full simulation toolbox for SEE available open-source due to licensing issues with some of the dependencies. In order to use the open-source SEE code available in this repository you can setup a simulation environment in Gazebo (ROS1) with a simulated LiDAR and process the pointclouds with SEE.
